run role: implement postconf based config for main.cf, master.cf

diff --git a/roles/run/tasks/config/default.yml b/roles/run/tasks/config/default.yml
--- a/roles/run/tasks/config/default.yml
+++ b/roles/run/tasks/config/default.yml
@@ -233,87 +233,137 @@
         mode: "{{ __run_postfix_mastercf_mode }}"
       }
 
-
-# Prevent harmless but annoying 'overriding earlier entry' warnings
-- name: "Config | Default | main.cf: Comment out managed but pre-defined values"
-  ansible.builtin.replace:
-    path: "{{ __run_postfix_maincf_file }}"
-    regexp: '^(([\t ]+)?({{ item["key"] }})([\t ]+)?=(.*))'
-    replace: '#\1'
-    before: "### BEGIN ANSIBLE MANAGED BLOCK ###"
-  loop: "{{ __run_postfix_merged_maincf_settings | dict2items | list }}"
-  when:
-    - __run_postfix_merged_maincf_settings is defined
-    - __run_postfix_merged_maincf_settings
-
-
 # Notes on the main.cf handling:
 #
-# * Sadly, it is not possible to import other config files into main.cf.
-#   So one has to edit the existing file.
+# - For details on the format of the file, see the postconf(5) manual page
+#   (command: "man 5 postconf" or on-line:  https://www.postfix.org/postconf.5.html).
 #
-# * From https://www.postfix.org/postconf.5.html:
-#
+# - From https://www.postfix.org/postconf.5.html:
 #   > When the same parameter is defined multiple times, only the last
 #   > instance is remembered. Otherwise, the order of main.cf parameter
 #   > definitions does not matter.
+#   Please note that overwriting values will produce warnings.
 #
-#   Because of this behavior and the fact that the main.cf the distributions
-#   ships vary a lot (e.g. Debian is minimalistic while Red Hat-like
-#   contain nearly every setting commented out beside inline documentation),
-#   we decided to maintain an Ansible managed settings block at the end of the
-#   file. Additionally, it makes no sense to just map a subset of settings to a
-#   list. Therefore we simply pass a dict.
-- name: "Config | Default | main.cf: Update settings"
-  ansible.builtin.blockinfile:
-    path: "{{ __run_postfix_maincf_file }}"
-    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
-    # The config does not quote strings and allows multiline values, so the loop is simple
-    block: |
+# - Sadly, it is not possible to import other config files, so one has to edit
+#   the existing config file inline.
+#
+# - The shipped main.cf on platforms vary a lot (e.g. Debian is minimalistic
+#   while Red Hat-like contain nearly every setting commented out beside
+#   inline documentation).
+- name: "Config | Default | Update main.cf"
+  # The command or shell module is used here. This approach is justified:
+  #
+  # - No built-in Ansible module provides a direct way to interact with the
+  #   Postfix configuration
+  # - We first uses [lineinfile|blockinfile], but it had major downsides:
+  #   1. The need to comment out already-defined values to prevent warnings.
+  #   2. The great variation on different platforms may trigger high maintenance
+  #      for regexes and edge-cases, changed_when, ...
+  #   Using postconf in a loop seems to be the sanest way to handle the config.
+  #
+  # Notes on the command or script itself:
+  #
+  # See the official documentation for a explanation of the parameters:
+  # https://www.postfix.org/postconf.1.html
+  ansible.builtin.shell:
+    cmd: |
+      set -u # fail on unset vars
+      set -o pipefail # fail if any pipe cmd fails
+
+      __run_postfix_checksum_before="$({{ __run_postfix_sha1sum_executable }} {{ __run_postfix_maincf_file | ansible.builtin.quote }})"
+
+      set -e # exit on any error (incl. in if/while/tests)
       {% for key, value in __run_postfix_merged_maincf_settings.items() %}
-      {{ key }} = {{ value }}
+      {{ __run_postfix_postconf_executable }} -e {{ key | ansible.builtin.quote }}={{ value | ansible.builtin.quote }}
       {% endfor %}
+      set +e # no exit on any error (if/while/tests needed in the following)
+
+      __run_postfix_checksum_after="$({{ __run_postfix_sha1sum_executable }} {{ __run_postfix_maincf_file | ansible.builtin.quote }})"
+      if [ "${__run_postfix_checksum_before}" != "${__run_postfix_checksum_after}" ]
+      then
+        printf 'Changed config file: {{ __run_postfix_maincf_file }}'
+      fi
+
+      exit 0
+    executable: "/bin/bash" # this inline script was only tested with Bash yet, so hardcode the shell
   when:
     - __run_postfix_merged_maincf_settings is defined
+  changed_when:
+    - __run_postfix_config_maincf_result.rc == 0
+    - "'Changed config file' in __run_postfix_config_maincf_result.stdout"
+  register: __run_postfix_config_maincf_result
   notify:
     - "run_postfix: update lookup tables"
     - "run_postfix: update aliases"
     - "run_postfix: reload postfix.service"
 
 
-# Prevent harmless but annoying 'warning: duplicate master.cf entry for service' warnings
-- name: "Config | Default | master.cf: Comment out managed but pre-defined values"
-  ansible.builtin.replace:
-    path: "{{ __run_postfix_mastercf_file }}"
-    regexp: '^(([\t ]+)?({{ item["key"] }})([\t ]+)(.*){{ item["value"]["type"] }})'
-    replace: '#\1'
-    before: "### BEGIN ANSIBLE MANAGED BLOCK ###"
-  loop: "{{ __run_postfix_merged_mastercf_settings | dict2items }}"
-  when:
-    - __run_postfix_merged_mastercf_settings is defined
-    - __run_postfix_merged_mastercf_settings
-
 
 # Notes on the master.cf handling:
 #
-# * For details on the format of the file, see the master(5) manual page
+# - For details on the format of the file, see the master(5) manual page
 #   (command: "man 5 master" or on-line: http://www.postfix.org/master.5.html).
 #
-# * Sadly, it is not possible to import other config files into master.cf.
-#   So one has to edit the existing file.
+# - Sadly, it is not possible to import other config files, so one has to edit
+#   the existing config file inline.
 #
-# * When multiple lines specify the same service name and type, only the last
-#   one is remembered.
-- name: "Config | Default | master.cf: Update settings"
-  ansible.builtin.blockinfile:
-    path: "{{ __run_postfix_mastercf_file }}"
-    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
-    # The config does not quote strings and allows multiline values, so the loop is simple
-    block: |
+# - When multiple lines specify the same service name and type, only the last
+#   one is remembered. Please note that overwriting services will produce
+#   warnings.
+#
+# - The shipped master.cf on platforms vary a lot.
+
+- name: "Config | Default | Update master.cf"
+  # The command or shell module is used here. This approach is justified:
+  #
+  # - No built-in Ansible module provides a direct way to interact with the
+  #   Postfix configuration
+  # - We first uses [lineinfile|blockinfile], but it had major downsides:
+  #   1. The need to comment out already-defined values to prevent warnings.
+  #   2. The great variation on different platforms may trigger high maintenance
+  #      for regexes and edge-cases, changed_when, ...
+  #   Using postconf in a loop seems to be the sanest way to handle the config.
+  #
+  # Notes on the command or script itself:
+  #
+  # See the official documentation for a explanation of the parameters:
+  # https://www.postfix.org/postconf.1.html
+  ansible.builtin.shell:
+    cmd: |
+      set -u # fail on unset vars
+      set -o pipefail # fail if any pipe cmd fails
+
+      __run_postfix_checksum_before="$({{ __run_postfix_sha1sum_executable }} {{ __run_postfix_mastercf_file | ansible.builtin.quote }})"
+
+      set -e # exit on any error (incl. in if/while/tests)
       {% for service, fields in __run_postfix_merged_mastercf_settings.items() %}
-      {{ service }} {{ fields['type'] }} {{ fields['private'] }} {{ fields['unpriv'] }} {{ fields['chroot'] }} {{ fields['wakeup'] }} {{ fields['maxproc'] }} {{ fields['command_args'] }}
+      {{ __run_postfix_postconf_executable }} -M {{ service ~ '/' ~ fields['type'] | ansible.builtin.quote }}={{
+        (
+          service ~ ' ' ~
+          fields['type'] ~ ' ' ~
+          fields['private'] ~ ' ' ~
+          fields['unpriv']  ~ ' ' ~
+          fields['chroot']  ~ ' ' ~
+          fields['wakeup']  ~ ' ' ~
+          fields['maxproc']  ~ ' ' ~
+          fields['command_args']
+        ) | ansible.builtin.quote }}
       {% endfor %}
+      set +e # no exit on any error (if/while/tests needed in the following)
+
+      __run_postfix_checksum_after="$({{ __run_postfix_sha1sum_executable }} {{ __run_postfix_mastercf_file | ansible.builtin.quote }})"
+      if [ "${__run_postfix_checksum_before}" != "${__run_postfix_checksum_after}" ]
+      then
+        printf 'Changed config file: {{ __run_postfix_mastercf_file }}'
+      fi
+
+      exit 0
+    executable: "/bin/bash" # this inline script was only tested with Bash yet, so hardcode the shell
   when:
     - __run_postfix_merged_mastercf_settings is defined
+  changed_when:
+    - __run_postfix_config_mastercf_result.rc == 0
+    - "'Changed config file' in __run_postfix_config_mastercf_result.stdout"
+  register: __run_postfix_config_mastercf_result
   notify:
-    - "run_postfix: reload postfix.service"
+    - "run_postfix: restart postfix.service"
